### ISSUE TITLE
go version 1.20 is out!

### ISSUE THREAD

**Issue by JvGinkel** [longsleep/golang-deb#11]
Hi, 

First of all thank you for your work, It makes it really easy to install golang on ubuntu!

If you have some time can you please add golang version 1.20?

Thanks!

**Comment by longsleep** [comment]
It will happen, please be a little patient :+1:

**Comment by longsleep** [comment]
1.20 has been published to the ppa - install golang-1.20 to get it. After successfultesting, golang-defaults will be bumped to 1.20 too.
