### ISSUE TITLE
Go 1.22

### ISSUE THREAD

**Issue by TomOne** [longsleep/golang-deb#13]
First of all, thank you for your great work on this project! ❤ Having a PPA for Go is fantastic. Are you planning to release packages for Go 1.22 too?

**Comment by longsleep** [comment]
Yes, as soon as I have the time. Last weeks were busy - sorry for the delay, but it will happen soon.

**Comment by longsleep** [comment]
Packages for 1.22 are now in the ppa. Will be bumped to default after a little testing. Closing.

**Comment by TomOne** [comment]
That’s great, thanks a lot!
