### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by MrSerth** [longsleep/golang-deb#14]
Many thanks for your great work to provide these packages! 🙏

We would really appreciate if you could add support for Ubuntu 24.04 Noble already. While I know that [Ubuntu 24.04 ships with Golang 1.22.2](https://packages.ubuntu.com/noble/golang-1.22-go), the newest patch version 1.22.3 is not easily available as a package. Thus, similar to #9, a release would be beneficial already.

**Comment by longsleep** [comment]
I will happen once I have time to complete testing. You can help by installing the existing focal builds from the ppa on Ubuntu 24.04 and report back here that it installs fine and generally works.

**Comment by longsleep** [comment]
Noble has been added to the published packages of the PPA and seems to work fine. Closing this here.

**Comment by MrSerth** [comment]
Awesome, thank you! Even faster than I was able to test the focal package 👍
