### ISSUE TITLE
Go 1.23

### ISSUE THREAD

**Issue by MrSerth** [longsleep/golang-deb#17]
Go 1.23 has been released ([more information and release notes here](https://go.dev/doc/go1.23)) 🥳.

I assume you are already aware of the release and will probably draft a new release as time permits -- thank you for your open source commitment! Hence, I just created this issue for visibility.

**Comment by longsleep** [comment]
Sure - it will happen as soon as I find the time in the next couple of days 👍

**Comment by longsleep** [comment]
Packages for Go 1.23 are now available in the PPA. Please help testing. They will be promoted to default soon. Closing this here.

**Comment by gwatts** [comment]
@longsleep confirmed works great for me; rebuilt our product using it, ran tests etc, no problems.

Many thanks for your continued work maintaining this resource!

**Comment by MrSerth** [comment]
Same for us; we already deployed the new package and everything works flawlessly.

Thank you for your open source commitment and all the great work you do!
