### ISSUE TITLE
Automatic version updates, e.g. for updating to 1.23.2

### ISSUE THREAD

**Issue by satmandu** [longsleep/golang-deb#18]
Any chance of setting up a github action to automatically generate packages for point releases of golang?

The current version can be pulled using `git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/golang/go '*.*.*' | grep -v "release.\|weekly." | tail --lines=1 | cut --delimiter='/' --fields=3 | sed 's/go//'`

**Comment by longsleep** [comment]
I am not sure if that is even easily possible. I also do not see much of the point? What would that gain other than potentially speeding up point releases becoming available?

**Comment by satmandu** [comment]
I'm creating a docker container for our self-hosted GitHub actions runner, and the go version in the container gets flagged with security issues (by docker hub), so I'm installing the current point version directly, but it would be cleaner to do it with a ppa so an `apt update && apt upgrade -y` would take care of that without having to manually download the current version.

**Comment by longsleep** [comment]
Well point releases are available in the ppa within a couple of days. If you ware that security depending on go point version updates you should probably keep doing what you are doing.

Closing this for now as I don't plan to automate updates.
