### ISSUE TITLE
Symlinks in go-1.13 break godoc

### ISSUE THREAD

**Issue by coventry** [longsleep/golang-deb#3]
I was able to get `godoc` going by copying the original directories `api`, `pkg/include`, `test`, `misc` and `src` from `/usr/share/go-1.13` onto the corresponding symlinks in `/usr/lib/go-1.13`. Prior to that, it was failing with 

```
using module mode; GOMOD=/home/ubuntu/alien/tools/go.mod
2020/02/12 20:47:19 godoc: corpus fstree is nil
```

It would be good if these weren't symlinks; the golang team [isn't planning to fix this issue](https://github.com/golang/go/issues/15049#issuecomment-346414739). Absent that, it would be good if there were a warning on the PPA website that this breaks `godoc` due to those symlinks, along with a description of a workaround.

**Comment by longsleep** [comment]
This packaging will not divert from Debian packaging (its a backport). If this is a concern, please open the corresponding issue in the Debian bugtracker.
