### ISSUE TITLE
go-1.16.2 build fails for i386 arch

### ISSUE THREAD

**Issue by dwillist** [longsleep/golang-deb#5]
Hey longsleep, looks like the [`i386` lanuchpad build is broken](https://launchpadlibrarian.net/527454516/buildlog_ubuntu-bionic-i386.golang-1.16_1.16.2-1longsleep1+bionic_BUILDING.txt.gz). I've poked around at the `rules` file to see if I could get something working without much luck.

**Comment by longsleep** [comment]
Yes - it's a known issue and the current plan is to drop i386 from the ppa.

Go 1.16 requires a newer Go than the one which is available on the current build platform to build on i386.

**Comment by dwillist** [comment]
Gotcha thanks for the quick response 👍

**Comment by longsleep** [comment]
Closing this one, as it remains a won't fix.
