### ISSUE TITLE
1.18 on Hirsute

### ISSUE THREAD

**Issue by jbblanchet** [longsleep/golang-deb#8]
LONG time user of your golang PPA, thanks for the work you've put into it.

I noticed that 1.18 wasn't made available for Hirsute Hippo. We can't use Focal because of some compatibility issues with the new Macs, and 22.04 is a month away. Do you plan on making that combination available? Couldn't find any documentation about what versions you support anywhere.

**Comment by longsleep** [comment]
Hi,

Hirsute is end of life thus I cannot publish anything for it anymore. PPA
supports the latest two LTS releases and the current non LTS when feasible.

Cheers
Simon

**Comment by jbblanchet** [comment]
Thanks for the update. We can't update to 21.10 yet, I'll find an alternative solution for now.
