### ISSUE TITLE
Ubuntu 22.04 support

### ISSUE THREAD

**Issue by zlianon** [longsleep/golang-deb#9]

**Comment by longsleep** [comment]
As of now there is no need, as Ubuntu 22.04 contains the currently latest Go (1.18). The PPA will support Go 1.19 once it becomes available and then also provide Ubuntu 22.04 builds.

Is there another reason why you want Ubuntu 22.04 support now @zlianon ?

**Comment by alexandrethiel** [comment]
@longsleep main reason is:
Offical jammy ubuntu repo is using 1.18.1: https://packages.ubuntu.com/jammy/golang-1.18-go
In the PPA, we now have 1.18.3 for impish but not for jammy. That's a bit odd

+1 for jammy support for 1.18

**Comment by longsleep** [comment]
@alexandrethiel OK that makes a lot of sense. I just triggered the publish for "jammy" and it should be available in a few minutes. Please let me know if it works and i will continue to publish new versions also for jammy and close this ticket.

**Comment by longsleep** [comment]
Seems that it works, closing.
